"""fix sentences

Revision ID: 5bca04bb04f5
Revises: c960dcc75b01
Create Date: 2022-02-17 04:20:59.864241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bca04bb04f5'
down_revision = 'c960dcc75b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sentence_text_id_fkey', 'sentence', type_='foreignkey')
    op.create_foreign_key(None, 'sentence', 'text', ['text_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sentence', type_='foreignkey')
    op.create_foreign_key('sentence_text_id_fkey', 'sentence', 'author', ['text_id'], ['id'])
    # ### end Alembic commands ###
