"""rm example parses

Revision ID: 7fda2b257870
Revises: b4a3ef734ee1
Create Date: 2022-06-16 22:31:46.545143

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7fda2b257870'
down_revision = 'b4a3ef734ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ccgparse', 'interpretation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('exampleccgparse_example_id_fkey', 'ccgparse', type_='foreignkey')
    op.drop_column('ccgparse', 'example_id')
    op.alter_column('constituencyparse', 'interpretation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('exampleconstituencyparse_example_id_fkey', 'constituencyparse', type_='foreignkey')
    op.drop_column('constituencyparse', 'example_id')
    op.alter_column('dependencyparse', 'interpretation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('exampledependencyparse_example_id_fkey', 'dependencyparse', type_='foreignkey')
    op.drop_column('dependencyparse', 'example_id')
    op.add_column('interpretation', sa.Column('paraphrase', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interpretation', 'paraphrase')
    op.add_column('dependencyparse', sa.Column('example_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('exampledependencyparse_example_id_fkey', 'dependencyparse', 'example', ['example_id'], ['id'])
    op.alter_column('dependencyparse', 'interpretation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('constituencyparse', sa.Column('example_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('exampleconstituencyparse_example_id_fkey', 'constituencyparse', 'example', ['example_id'], ['id'])
    op.alter_column('constituencyparse', 'interpretation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('ccgparse', sa.Column('example_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('exampleccgparse_example_id_fkey', 'ccgparse', 'example', ['example_id'], ['id'])
    op.alter_column('ccgparse', 'interpretation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
