"""move parses to interpretations

Revision ID: b4a3ef734ee1
Revises: f88f6763f62f
Create Date: 2022-06-16 21:03:51.228958

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b4a3ef734ee1'
down_revision = 'f88f6763f62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ccgparse', sa.Column(
        'interpretation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ccgparse', 'interpretation',
                          ['interpretation_id'], ['id'])
    op.add_column('constituencyparse', sa.Column(
        'interpretation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'constituencyparse', 'interpretation', [
                          'interpretation_id'], ['id'])
    op.add_column('dependencyparse', sa.Column(
        'interpretation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dependencyparse', 'interpretation', [
                          'interpretation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dependencyparse', type_='foreignkey')
    op.drop_column('dependencyparse', 'interpretation_id')
    op.drop_constraint(None, 'constituencyparse', type_='foreignkey')
    op.drop_column('constituencyparse', 'interpretation_id')
    op.drop_constraint(None, 'ccgparse', type_='foreignkey')
    op.drop_column('ccgparse', 'interpretation_id')
    # ### end Alembic commands ###
