"""interpretation table

Revision ID: f88f6763f62f
Revises: 76b6c171aa58
Create Date: 2022-06-16 19:54:45.761918

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f88f6763f62f'
down_revision = '76b6c171aa58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interpretation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('example_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['example_id'], ['example.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'example', 'fragment', ['fragment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'example', type_='foreignkey')
    op.drop_table('interpretation')
    # ### end Alembic commands ###
