"""parse tables

Revision ID: 72e8598dbbd5
Revises: 8246264df318
Create Date: 2022-04-28 15:44:40.303796

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '72e8598dbbd5'
down_revision = '8246264df318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exampleccgparse',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('parse_string', sa.String(), nullable=True),
                    sa.Column('example_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['example_id'], ['example.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('exampleconstituencyparse',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('parse_string', sa.String(), nullable=True),
                    sa.Column('example_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['example_id'], ['example.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('exampledependencyparse',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('parse_string', sa.String(), nullable=True),
                    sa.Column('example_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['example_id'], ['example.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('author', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('author', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_index('ix_author_full_name', table_name='author')
    op.drop_index('ix_author_id', table_name='author')
    op.drop_column('author', 'full_name')
    op.alter_column('example', 'text_id', nullable=False, new_column_name='fragment_id')
    op.drop_index('ix_example_id', table_name='example')
    op.drop_constraint('sentence_text_id_fkey', 'example', type_='foreignkey')
    op.drop_column('example', 'has_punctuation')
    op.alter_column('fragment', 'author_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_index('ix_fragment_id', table_name='fragment')
    op.drop_index('ix_user_id', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_fragment_id', 'fragment', ['id'], unique=False)
    op.alter_column('fragment', 'author_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.add_column('example', sa.Column('has_punctuation',
                  sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('example', 'fragment_id', nullable=False, new_column_name='text_id')
    op.drop_constraint(None, 'example', type_='foreignkey')
    op.create_foreign_key('sentence_text_id_fkey', 'example',
                          'fragment', ['text_id'], ['id'])
    op.create_index('ix_example_id', 'example', ['id'], unique=False)
    op.drop_column('example', 'fragment_id')
    op.add_column('author', sa.Column('full_name', sa.VARCHAR(),
                  autoincrement=False, nullable=True))
    op.create_index('ix_author_id', 'author', ['id'], unique=False)
    op.create_index('ix_author_full_name', 'author', ['full_name'], unique=False)
    op.drop_column('author', 'last_name')
    op.drop_column('author', 'first_name')
    op.drop_table('exampledependencyparse')
    op.drop_table('exampleconstituencyparse')
    op.drop_table('exampleccgparse')
    # ### end Alembic commands ###
