"""add sentences

Revision ID: c960dcc75b01
Revises: 4bd691a797f6
Create Date: 2022-02-17 04:03:59.605942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c960dcc75b01'
down_revision = '4bd691a797f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.Column('parse_string', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_id'), 'sentence', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentence_id'), table_name='sentence')
    op.drop_table('sentence')
    # ### end Alembic commands ###
