"""text slug

Revision ID: f0407e4e95d8
Revises: 5cd48b1b14d2
Create Date: 2022-04-27 22:11:55.091506

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f0407e4e95d8'
down_revision = '5cd48b1b14d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sentence', 'has_punctuation',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('sentence', 'parse_type',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.add_column('text', sa.Column('slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'text', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text', type_='unique')
    op.drop_column('text', 'slug')
    op.alter_column('sentence', 'parse_type',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('sentence', 'has_punctuation',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    # ### end Alembic commands ###
